"""
Zig multi-line strings make it easy to define a docstring...

..with lots of lines!

P.S. I'm sure one day we'll hook into Zig's AST and read the Zig doc comments ;)
"""
from __future__ import annotations

def count(): ...
def hello(name, /): ...
def increment(): ...
def whoami(): ...

class submod:
    def world(): ...
