name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: write

env:
  POETRY_VERSION: "2.1.2"
  PYTHON_VERSION: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          # Needed for docs to discover gh-pages branch
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.POETRY_VERSION  }}-${{ steps.setup-python.outputs.python-version }}
      - name: Install Poetry
        id: install-poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
        # If changing any of these, you must comment out the if statement above.
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Poetry git plugin
        run: poetry self add poetry-git-version-plugin

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Poetry Install
        run: poetry install -n -v
      - name: Poetry Build
        run: poetry build -v

      - name: Ruff
        run: poetry run ruff check .
      - name: Black
        run: poetry run ruff format --check .
      - name: Run library tests
        run: poetry run python -m ziglang build test
      - name: Pytest
        run: poetry run pytest
      - name: Check generated stubs
        run: poetry run python -m ziglang build --build-file pytest.build.zig generate-stubs -Dcheck-stubs=true
      - name: Zig Docs Build
        run: poetry run python -m ziglang build docs
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@dummy.bot.com
      - name: MKDocs Build
        run: poetry run mike deploy develop --push
        if: ${{ github.ref == 'refs/heads/develop' }}
